### ISSUE TITLE
Store journal messages / snapshots in BSON

### ISSUE THREAD

**Issue by alari** [ironfish/akka-persistence-mongo#88]
Hi.

I want to implement EventSourcing, but also -- to be able to query events to get some analytics, and to change my event models without binary compatibility.

Mongo stores objects in BSON. Having BSON => Message and Message => BSON (de)serializers, I can achieve all of this.

Is it reasonable to add such an ability to akka-persistence-mongo? For example, we could have custom config flag ".preserve-bson = false". If bson object is passed and config flag is turned on, then store it as-is. If flag is off, always serialize object to blob.

It's user's duty to perform (de)serisalization.

What do you think?

**Comment by ironfish** [comment]
Hi Alari,

The main challenge behind storing the event as BSON is hydration. The journal must agnostically dehydrate and hydrate events and relies on the serializer (which needs schema/IDL support) to manage type semantics. To my knowledge, BSON serialization does not have schema/IDL and therefore does not contain the proper meta-data to rehydrate the event.

In order to use BSON serialization, the event would need to contain a schema serialized version of the event (meta-data) so we could reflectively rehydrate, which would most definitely impact performance. This approach however introduces new potential challenges. If the included meta-data is not correct, then the rehydration process would fail.

I'm open to suggestions.

**Comment by alari** [comment]
Hi Ironfish.

My suggestion is just to store BSON as-is.

If an event is sent to persist() in BSON, store it as BSON.

If retrieved event is in BSON and is not a single blob, send it to receiveRecover as-is, in BSON.

So that the plugin never tries to understand the inner structure of BSON document: it's not the persister's job, not a part of akka-persistence API and so on. User must handle it (if he needs to) in his persistent actor.

**Comment by ironfish** [comment]
Okay, now I see what your saying. Yes I think that would be doable. I plan to do a release today and will put this feature in the next version, so leave this issue open and I will mark complete once it is implemented.

**Comment by alari** [comment]
That's great, thanks!

Please tell me if I can help

**Comment by jochenchrist** [comment]
+1

**Comment by sourcekick** [comment]
+1

**Comment by hekailiang** [comment]
Any update on this issue? What should I do if I want to store messages in BSON?

**Comment by hekailiang** [comment]
Since what I want is a readable message, I found a simple solution that is to add additional field(e.g. event) in persistent events to store the event content. And then override the "casbah-journal.class" with extended class. 
```scala
ackage akka.persistence.mongo.journal

import akka.persistence.PersistentRepr
import com.mongodb.casbah.Imports._

private[persistence] class MyCasbahJournal extends CasbahJournal {

  val EventKey = "event"

  override def writeJSON(pId: String, sNr: Long, pr: PersistentRepr) = {
    val builder = MongoDBObject.newBuilder
    builder += PersistenceIdKey -> pId
    builder += SequenceNrKey    -> sNr
    builder += MarkerKey        -> MarkerAccepted
    builder += MessageKey       -> toBytes(pr)
    builder += EventKey         -> pr.payload.toString
    builder.result()
  }
}
```

**Comment by Dris101** [comment]
Hi all. I agree this is an important issue, not just for this plugin, but for Akka persistence in general. I have attempted a first cut at something along these lines. I implemented a marker trait, akka.persistence.mongo.BsonPersistable, and changed the writeJson method of CasbahJournaHelper to
```scala
def writeJSON(pId: String, sNr: Long, pr: PersistentRepr) = {
    val decoder = new BasicBSONDecoder()
    val builder = MongoDBObject.newBuilder
    builder += PersistenceIdKey -> pId
    builder += SequenceNrKey -> sNr
    builder += MarkerKey -> MarkerAccepted
   
    pr.payload match {
      case payload: BsonPersistable =>
        val bytes = toBytes(payload)
        val bson = Try(decoder.readObject(bytes))
        val result = bson match {
          case Success(bson) => bson
          case Failure(f) =>
            log.error(f, s"BSON serialization error for payload $payload")
            "Serialization error"
        }
        builder += BSONDocKey -> result

      case _ =>  builder += MessageKey -> toBytes(pr)
    }
    builder.result()
  }
```
I then changed the replay method of CasbahRecovery to
```scala
private def replay(persistenceId: String, fromSequenceNr: Long, toSequenceNr: Long, max: Long)(replayCallback:
      PersistentRepr => Unit): Unit = {

    import com.mongodb.casbah.Implicits._

    val encoder = new BasicBSONEncoder()
    val coll = collection.find(replayFindStatement(persistenceId, fromSequenceNr, toSequenceNr)).sort(recoverySortStatement)
    val collSorted = immutable.SortedMap(coll.toList.zipWithIndex.groupBy(x => x._1.as[Long](SequenceNrKey)).toSeq: _*)
    collSorted.flatMap { x =>
      if (x._2.headOption.get._2 < max) {
        val entry: Option[PersistentRepr] = x._2.find(_._1.get(MarkerKey) == MarkerAccepted).map(_._1).map {e =>
          if (e.containsField(BSONDocKey)) {
            val bson = e.as[MongoDBObject](BSONDocKey)
            val clazz = Class.forName(bson.as[String](TypeKey))
            val s = serialization.serializerFor(clazz)
            val payload = s.fromBinary(encoder.encode(bson), Some(clazz))
            PersistentRepr(payload, e.as[Long](SequenceNrKey))
          } else {
            val bytes = e.as[Array[Byte]](MessageKey)
            fromBytes[PersistentRepr](bytes)
          }
        }
        val deleted = x._2.exists(_._1.get(MarkerKey) == MarkerDelete)
        val confirms = x._2.filter(_._1.as[String](MarkerKey).substring(0,1) == MarkerConfirmPrefix).map(_._1.as[String](MarkerKey).substring(2)).to[immutable.Seq]
        log.debug(entry.toString)
        if (entry.nonEmpty) Some(entry.get.update(deleted = deleted, confirms = confirms)) else None
      } else None
    } map replayCallback
  }
```
This requires a standard Akka serializer to be in place to take the byte array and rehydrate the type. It expects the name of the type to have been stored in the BSON document under the TypeKey field. I have written a serializer (along the lines of the Akka protocol buffer serializer) which does this by expecting the payload classes to inherit from a BSONSerializable trait which has a toBson method returning a MongoDBObject with the serialized class in it for serialization, and to implement a method on the companion object taking a MongoDBObject and return an instance of the class for deserialization. It does wind up roundtripping between byte arrays, BSON and the class which isn't great for efficiency however. If any of that looks sensible I can post the code of the serializer or fork the project properly. Thanks for all the work on this plugin.

**Comment by manuelbernhardt** [comment]
@Dris101 this looks quite promising. Did you at all consider using [Salat](http://github.com/novus/salat) for this purpose? Salat was built for the purpose of serializing and deserializing case classes and works really quite well (it also performs very well, and is based on pickles). It also uses a type hint to know which class to deserialize into. Essentially it would cut quite some boilerplate.

More on the use-case: as I see it, having the means to write events in BSON opens up for interesting use-cases, such as being able to perform analytics etc. directly on replicated store nodes. I'm not sure as to the impact on performance this approach has (as opposed to other serialization strategies), but having the possibility to see the data in the journal & query it would in my opinion be a very nice feature to have - especially in those cases where things go wrong.

**Comment by Dris101** [comment]
Many thanks. I have looked at Salat amongst others, Scala Pickles (which might also be useful going via JSON) and Play's JSON serializers. What my Akka serializer does is ask you to provide a method for producing your case classes from a MongoDBObject and for producing a MongoDBObject from a case class instance but isn't opinionated about how you do that. There should be nothing stopping you from using Salat or rolling your own within those methods. I have had to go via Array[Byte] to make use of the Akka serialization infrastructure hence going:- case class -> MongoDBObject -> Bytes-> MongoDBObject -> Database. I'll tidy up my code and post it to my fork shortly. I'd be interested in people's comments. I only got something semi-plausible working the other day.

**Comment by Dris101** [comment]
Rough cut at https://github.com/Dris101/akka-persistence-mongo/tree/bsonpersistence
Needs a running Mongo instance at localhost:27017 to run test (in SBT try testOnly Ser*). Test will fail if there any records in store.message.

**Comment by manuelbernhardt** [comment]
I had a quick look at this, it looks very nice. I am however wondering if we could find a way that would ease the integration with something like Salat. Say you have hundreds of different Event types, then it would be great to be able to define a materializer on a parent type instead of having to create hundreds of companion objects.

One idea (even though this starts to look like something rather complex for such a seemingly simple task) would be to define a sort of `MaterializerDiscoveryStrategy` which would be tasked with returning the materializer given a type. The default one would just look at the companion object. Then it would be possible to create a `SalatMaterializerDiscoveryStrategy` that would essentially just return a fitting materializer for the type and use Salat's grater in order to deserialize the class.

I'll see if I can fork your fork and come up with something.

One more thing: I had looked at scala-picking but I found the resulting JSON to be not very JSON-like (see [this issue](https://github.com/scala/pickling/issues/306)) - the [sbt serialization](http://github.com/sbt/serialization) project may be somewhat more fitting. For all things JSON I have now settled for [the sphere.io JSON macro](http://github.com/sphereio/sphere-scala-libs) which works very nicely with 300+ case classes (and saves a lot of boilerplate)

**Comment by manuelbernhardt** [comment]
I worked on this yesterday and got a [version](https://github.com/ironfish/akka-persistence-mongo/pull/90) that works on an application with a fair number of different event types.

This implementation does the following things:
- makes it possible to enable "pass-through" BSON serialization instead of binary serialization of the journal entry payload
- uses Salat to turn case classes (and if necessary other types) into BSON and vice-versa
- register custom BSON encoders / decoders (using Casbah's mechanism for this purpose)
- does not make use of Akka's standard serialization mechanism which targets binary serialization. Using that would mean two useless round-trips to / from binary, and that does not seem like a good thing.
- the design leaves the door open to use another approach than using Salat. The solution proposed by @Dris101 would simply not have been practical for the case I am working on, because implementing hundreds of toBSON / fromBSON methods wasn't very appealing.

It does not do anything regarding snapshots. If there is a need for that then I think it can be added later on. The use-case I feel is more attractive is to be able to query into the journal using MongoDB.

**Comment by Dris101** [comment]
Thanks Manuel. I really like this. It is much nicer than my approach. I have integrated your solution into a project I am working on using Cluster Sharding and have run into an immediate problem which is that at the moment it is an all-or-nothing approach to which case classes get grated and stored as BSON (either set casbah-journal.bson-serialization = "salat" or not). When it attempts to grate the messages the cluster sharding extension uses internally I am getting errors such as
```
com.novus.salat.util.MissingPickledSig

FAIL: class 'class akka.contrib.pattern.ShardCoordinator$Internal$ShardRegionRegistered' is missing both @ScalaSig and .class file!
```
Would there be an easy way of selecting which classes get the Salat treatment and which not? In my approach I employed a marker trait which did this as a useful side-effect. It would be potentially undesirable to do this with your system as you would have to add it to every case class you wanted grating (and your system nicely removes all the boilerplate and this would just add some back), but perhaps a config setting with a whitelist/blacklist regex on FQN that would be parsed by SalatBSONSerialization might do the trick?

**Comment by manuelbernhardt** [comment]
The error you're seeing is due to Salat not supporting nested classes. Though this event should probably not be persisted using Salat serialization. I didn't know these internal messages were persisted as well.

Rather than going after a specific set of messages, what do you think about excluding an entire processor? All we know of the messages to persist is the `PersistentRepr` which (at the moment) has access to the `processorId` through the `PersistentId` trait. That way it would be possible to exclude the internal akka actor(s) responsible for those messages (perhaps this should even be a default setting) of that kind of serialization. I am unsure as to the value of defining the type of serialization on the basis of a single message with this approach - that would allow to have a mix of binary and BSON messages for the same persistent actor, which would cause trouble when thinking in terms of analysis scenarios.

**Comment by Dris101** [comment]
One potential problem with screening on persistenceId is that you don't always know them ahead of time. For example with cluster sharding a typical definition would be
```scala
override def persistenceId: String = self.path.parent.name + "-" + self.path.name
```
While you are right that it doesn't seem great to mix BSON and binary (however its is derived, from protofbuf or whatever) for the same persistent actor, maybe you should be allowed to. It starts to couple Salat and persistence quite tightly otherwise. The spirit of Akka serialization is to do it on a class by class (or trait by trait) basis. It seems more natural to extend that into the choice of whether to use BSON or not. Clearly that is not very helpful in terms of implementation! I'll have a think.....

**Comment by manuelbernhardt** [comment]
You have a point that there's already a per-message-class design in place. It's somewhat unfortunate (but understandable) that the design of Akka Serialization limits its target format to binary as otherwise that infrastructure, including binding discovery mechanism as well as discovery based on a common super-class, could be reused here.

Before looking into a possible implementation path for per-class bindings, I am wondering if anyone else would have something to add here - @ironfish and @alari, any comments?

**Comment by ironfish** [comment]
Hi All - have been quite swamped preparing for ScalaDays, and other Typesafe stuff, but will review over the weekend, and also confer with some of our internal folks. I appreciated everyone's contribution in regards to this issue!

On a side note, yes (at least the last time I checked), Salat does not support nested classes, but there may be another way around this. Checkout [Quicklens - Deeply nested case class fields](http://www.warski.org/blog/2015/02/quicklens-modify-deeply-nested-case-class-fields/). The only issue is that it uses macros and I'm not sure I want to add this.

**Comment by Dris101** [comment]
I have implemented something which works for my current needs which is to add a config key casbah-journal.bson-whitelist which contains an array of regex. If any of them match the name of the class being serialized then it goes to BSON using @manuelbernhardt Salat solution, otherwise it just passes through to binary. I am happy to fork Manuel's repository and push my workaround, but I suspect that a more useful consensus will arise shortly!

**Comment by manuelbernhardt** [comment]
@ironfish just wondering, did you have time to look into this one a bit? We're using the Salat approach for a bit now, and so far it seems to work nicely (in a non-clustered environment). I'd be happy to contribute with improvements

**Comment by hekailiang** [comment]
Hi manuelbernhardt,  how can Java user also leverage this improvements? It seems that Salat only supports case class which is not available in Java.

**Comment by manuelbernhardt** [comment]
@hekailiang indeed this solution only works with Scala and case classes, which are somewhat easier to de/serialize

**Comment by ktoso** [comment]
Hi guys, 
Thanks for the discussion, I wanted to let you know we've been reading this thread intensely and it's been valuable feedback for us.

It does not seem to me that there there is a blocker for the feature; the implemented PR looks OK.
The answer for most of the discussion here is "simply do not use akka-serialization", which is perfectly fine (!), as it's specialised for `=> Bytes`. 

We noticed however that the translation from "domain model to XYZ model" is a common need, AND that we can provide something that would be useful for this as well as for upcasting. We're working on a draft now. The PR you have prepared @manuelbernhardt looks good, and I suggest to go ahead with it for the time being (for 2.3). The new feature will ease this but your current code will be possible to just adapt to the simpler model once we roll it into 2.4.

Thanks again and I'll ping here again once we have a PR with the new idea.

**Comment by prayagupa** [comment]
Any updates on this guys?? :hand:

**Comment by manuelbernhardt** [comment]
This seems to be dealt with [here](https://github.com/akka/akka/issues/17579). I have not had any time yet to adapt my application to the adapters (no pun intended) but it seems to [be rather easy](https://github.com/ktoso/akka/commit/7e86dac542292fab80bfa799f4d544b65e19fcc7#diff-e0e7ef1bbef9060ffe2afb1a0382f76cR533)

**Comment by ironfish** [comment]
thanks @manuelbernhardt for pointing out the model adapters. I'm going to close this as it's handled by Akka.
